env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {}
plugins:
  - coffeescript
globals:
  __DEV__: true
  DEBUG: true
  require: true
  __useCssModules__: true
  
